/** One command to execute and capture for EVIDENCE.md. */
export interface CommandSpec {
  /** Section title, e.g. "lint". */
  title: string;
  /** Executable name. */
  command: string;
  /** Arguments passed to the executable. */
  args: string[];
}

/** Captured result of running one command. */
export interface CommandResult {
  /** Section title copied from the spec. */
  title: string;
  /** Human-readable command line that was run. */
  commandLine: string;
  /** Process exit code; -1 when the process could not be spawned. */
  exitCode: number;
  /** Verbatim standard output. */
  stdout: string;
  /** Verbatim standard error. */
  stderr: string;
}

/** Environment facts recorded alongside command output. */
export interface RunMetadata {
  /** ISO 8601 timestamp of the run. */
  generatedAt: string;
  /** Git HEAD SHA at generation time, or a note when unavailable. */
  gitSha: string;
  /** True when the working tree had uncommitted changes. */
  workingTreeDirty: boolean;
  /** Absolute path of the repository root. */
  repoRoot: string;
  /** Node.js version string. */
  nodeVersion: string;
  /** ICU version bundled with the Node.js runtime. */
  icuVersion: string;
  /** tzdb version resolved by the Node.js runtime. */
  tzdbVersion: string;
}

const FENCE = '````';

function renderOutputBlock(label: string, content: string): string {
  const body = content.length === 0 ? '(empty)' : content.trimEnd();
  return `### ${label}\n\n${FENCE}\n${body}\n${FENCE}\n`;
}

/**
 * Renders EVIDENCE.md from captured command results and run metadata.
 * Output blocks are verbatim; nothing in them is edited or summarized.
 */
export function renderEvidence(
  metadata: RunMetadata,
  results: CommandResult[],
): string {
  const lines: string[] = [
    '# EVIDENCE.md',
    '',
    'Generated by scripts/evidence.ts. Do not edit by hand.',
    'Command output below is captured verbatim.',
    '',
    '## Run metadata',
    '',
    `- Generated: ${metadata.generatedAt}`,
    `- Git SHA: ${metadata.gitSha}${metadata.workingTreeDirty ? ' (working tree dirty)' : ''}`,
    `- Repo root: ${metadata.repoRoot}`,
    `- Node: ${metadata.nodeVersion}`,
    `- ICU: ${metadata.icuVersion}`,
    `- tzdb: ${metadata.tzdbVersion}`,
    '',
  ];
  results.forEach((result, index) => {
    lines.push(
      `## ${index + 1}. ${result.title}`,
      '',
      `Command: \`${result.commandLine}\``,
      '',
      `Exit code: ${result.exitCode}`,
      '',
      renderOutputBlock('stdout', result.stdout),
      renderOutputBlock('stderr', result.stderr),
    );
  });
  return `${lines.join('\n').trimEnd()}\n`;
}

const REPO_ROOT_LINE = /^- Repo root: (.+)$/m;
const VOLATILE_LINE = /^- (Generated|Git SHA|Repo root): .*$\n?/gm;
// The v8 coverage reporter prints this banner only in some environments
// (it is gated on a TTY / reporter setting), so it appears on CI but not
// locally. It is tooling noise, not evidence, so strip it on both sides.
const COVERAGE_BANNER = /^.*Coverage enabled with v8.*$\n?/gm;
const DURATION = /\b\d+(?:\.\d+)?\s?(?:ms|s)\b/g;
const CLOCK_TIME = /\b\d{2}:\d{2}:\d{2}\b/g;
// The cli-demo prints the byte length of its json output. That length
// includes the absolute vendored zoneinfo path in the receipt, which
// differs by machine, so mask the count. The reproducibility signal that
// matters, "bytes differing: 0" and "byte-identical: yes", is left exact.
const DEMO_BYTES = /^run \d+: \d+ bytes$/gm;

/**
 * Sorts the body of each top-level "## " section as one multiset. This
 * merges a command's stdout and stderr before comparison, because which
 * stream a tool writes a given line to is not stable across
 * environments (vitest, for one, splits its reporter and coverage
 * output across the two streams differently on CI than locally). The
 * content and the exit code of each command must still match exactly;
 * only line order and stream attribution within a command are relaxed.
 */
function sortLinesWithinSections(markdown: string): string {
  const lines = markdown.split('\n');
  const output: string[] = [];
  let buffer: string[] = [];
  const flush = (): void => {
    if (buffer.length > 0) {
      output.push(...buffer.toSorted());
      buffer = [];
    }
  };
  for (const line of lines) {
    if (line.startsWith('## ')) {
      flush();
      output.push(line);
    } else {
      buffer.push(line);
    }
  }
  flush();
  return output.join('\n');
}

/**
 * Normalizes a rendered EVIDENCE.md document for comparison across
 * runs and machines. Removes fields that legitimately differ between
 * two honest runs of the same commands on the same tree: the
 * generation timestamp, the git SHA line (an evidence file committed
 * with the code cannot contain the SHA of its own commit), the repo
 * root path, wall-clock durations, and clock times. Lines inside each
 * captured output block are compared as a sorted multiset, because
 * concurrent build tooling interleaves its log lines in
 * nondeterministic order between runs. Every output line and every
 * exit code must still match exactly.
 */
export function normalizeEvidence(markdown: string): string {
  const rootMatch = REPO_ROOT_LINE.exec(markdown);
  let normalized = markdown.replace(VOLATILE_LINE, '').replace(COVERAGE_BANNER, '');
  if (rootMatch !== null && rootMatch[1] !== undefined) {
    normalized = normalized.split(rootMatch[1]).join('<repo>');
  }
  return sortLinesWithinSections(
    normalized
      .replace(DURATION, '<duration>')
      .replace(CLOCK_TIME, '<time>')
      .replace(DEMO_BYTES, 'run: <bytes>'),
  );
}

/**
 * Returns a short human-readable description of the first line where
 * two normalized documents differ, or null when they are identical.
 */
export function firstDifference(a: string, b: string): string | null {
  if (a === b) {
    return null;
  }
  const aLines = a.split('\n');
  const bLines = b.split('\n');
  const max = Math.max(aLines.length, bLines.length);
  for (let i = 0; i < max; i += 1) {
    if (aLines[i] !== bLines[i]) {
      return [
        `First difference at normalized line ${i + 1}:`,
        `  committed: ${aLines[i] ?? '(missing)'}`,
        `  regenerated: ${bLines[i] ?? '(missing)'}`,
      ].join('\n');
    }
  }
  return 'Documents differ only in trailing whitespace.';
}
